stages:
  - test
  - qa

before_script:
  - export CACHE_KEY=$(sh scripts/generate_cache_key.sh)

cache:
  key: $CACHE_KEY
  paths:
    - vendor/
    - composer.lock

test:
  stage: test
  image: jefvda/php-composer
  before_script:
    - composer install --prefer-dist --no-progress --no-suggest
  script:
    - ./vendor/bin/phpunit

normalize-composer:
  stage: qa
  image: jefvda/php-composer
  before_script:
    - composer install --prefer-dist --no-progress --no-suggest
  script:
    - composer normalize --dry-run

php-cs-fixer:
  stage: qa
  image: jefvda/php-composer
  before_script:
    - composer install --prefer-dist --no-progress --no-suggest
  script:
    - ./vendor/bin/php-cs-fixer check --diff

phpstan:
  stage: qa
  image: jefvda/php-composer
  before_script:
    - composer install --prefer-dist --no-progress --no-suggest
  script:
    - ./vendor/bin/phpstan